# Generated by Django 3.2.7 on 2021-09-12 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Owner',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='user',
            new_name='owner',
        ),
    ]
