# Generated by Django 3.2.7 on 2021-09-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='books',
            field=models.ManyToManyField(to='books.Book'),
        ),
    ]
