# Generated by Django 3.2.7 on 2021-10-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_author_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'pub_date')},
        ),
    ]
