# Generated by Django 3.2.7 on 2021-10-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterUniqueTogether(
            name='owner',
            unique_together={('last_name', 'email')},
        ),
    ]
