# Generated by Django 3.2.7 on 2021-10-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20211001_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(max_length=60, unique=True),
        ),
    ]
