# Generated by Django 3.2.7 on 2021-11-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_owner_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
